### PR TITLE
More documentation for BaselineOf

### PR DESCRIPTION
**Pull request by theseion**
in the wake of #337.

### CODE REVIEW

**Comment by dalehenrich** [comment]
Since you had additional questions about `import:` and `import:provides:`, do you plan additional documentation updates? If so we can leave this PR open until you've finished your work ... for now:)

If you are finished for now, then I'll go ahead merge this puppy ... great work ...

**Comment by theseion** [comment]
Yes, I'd add documentation on `#import:`. You can leave it open.

**Comment by dalehenrich** [comment]
@theseion, I'm starting to emerge from my GemStone 3.3 hibernation is it time to merge your work into the master branch, or do you still have more work planned? BTW, I really appreciate this help!

**Comment by theseion** [comment]
:) no, that should be all from my point of view.
You're welcome.

**Pull request merged**
