### PR TITLE
add the platform attributes for 4.6 and 5.0 (for Metacello Preview)

### PR DESCRIPTION
**Pull request by pdebruic**
issue #365

### CODE REVIEW

**Comment by dalehenrich** [comment]
It looks like [the code for 1.0.0-beta.32.17 is no longer passing - these results do not include your changes](https://travis-ci.org/dalehenrich/metacello-work/builds/76676928)  ... I suspect tests have changed since then .. so I am seriously considering merging this without passing travis tests ... remind me why I thought that we needed to make these changes:)

**Comment by pdebruic** [comment]
After merging this change we will get a new SHA we can reference in the ConfigurationOfMetacelloPreview (which we will update then all over the place) to ensure that when someone using Squeak 4.6 or 5.0 runs an #ensureMetacello process they get a version of Metacello that knows about the platform attributes for Squeak 4.6 & 5.0.  

I think its fine to merge because it only affects the platform attributes on Squeak, and the code worksforme.....

**Comment by dalehenrich** [comment]
Now I will start work on updating the Configuration ... open an issue for tracking

**Comment by pdebruic** [comment]
We started the configuration on Friday I think.  I've got it on my laptop.  I'll push it and make a PR.

**Comment by dalehenrich** [comment]
Whoops, I made the same edits earlier this afternoon: bda06bff03992bab0d1af428c2e26bc038e77f25 ... seeing lots of test failures on both yours and mine - I assume that the problem is that we're hitting github api rate limits running the tests ...  I've been restarting my tests and I think they are passing ... so I'm going to nuke your test run and go with my edits since the tests are further along ...

**Comment by pdebruic** [comment]
Sounds good.

**Comment by krono** [comment]
*patiently waiting* :)

**Comment by pdebruic** [comment]
@krono see the comment on issue #365 ...

**Comment by dalehenrich** [comment]
Sorry @krono, I've got a lot of things on my plate right now and if the 
tests all ran green it would be much easier for me to just press a merge 
button ... I have yet to see 4.6 and/or 5.0 pass on travis either ...

**Comment by krono** [comment]
No problem :)

**Pull request merged**
