### PR TITLE
Push cache driectory to concrete classes

### PR DESCRIPTION
**Pull request by krono**
- Metacello-GitBasedRepository-topa.14
 - Metacello-Bitbucket-topa.6
 - Metacello-GitHub-topa.46

### CODE REVIEW

**Comment by krono** [comment]
@dalehenrich any comments?

**Comment by krono** [comment]
Test failures only due to #348

**Comment by dalehenrich** [comment]
I presume that this is a bugfix for Issue #347 (which actually post-dates this PR:)

**Comment by krono** [comment]
yep

**Comment by krono** [comment]
All running except for one. What do you think?

**Comment by dalehenrich** [comment]
I am rerunning the test .. it's a little disturbing that the error happens to be in bitbucket test, but I cannot guess how the changes you made would cause a test to Error out ... I love that you updated the docs!

I'lll wait fo the test to run and then *merge with cautione*:)

**Comment by krono** [comment]
Ok.

**Comment by krono** [comment]
Btw: The doc updates somehow slipped in here, don't ask me.
They were not in here initially. I think there's been a slip by github, but nevertheless, the docu by Max seems helpful

**Comment by dalehenrich** [comment]
Hmmm, I've seen some of these commits like that show up merges in other projects ... makes you wonder a bit, but it seems to be benign ... the test is green (bitbucket network failure most likely), so we this puppy will be merged shortly ...

**Comment by krono** [comment]
\o/

**Pull request merged**
