### PR TITLE
Add Pharo 5.0 to the line up.

### PR DESCRIPTION
**Pull request by demarey**

### CODE REVIEW

**Comment by dalehenrich** [comment]
[This error `Working copy for Metacello-TestsCommonMC.pharo20-dkh.5 not found`](https://travis-ci.org/dalehenrich/metacello-work/jobs/64599476#L364) is possibly due to the fact that the BaselineOfMetacello does not have a spec for `#'pharo5.x'` (should be added [here](https://github.com/dalehenrich/metacello-work/blob/master/repository/BaselineOfMetacello.package/BaselineOfMetacello.class/instance/baseline..st#L207-223)) ... OTOH (it is very hard for me to read the stack report from the pharo debug log in travis),  there might be some confusion in the bootstrapping code ... in which case Metacello must think that it isn't installed yet ...

Have you been able to manually install Metacello in Pharo5.0 using the following:

```Smaltalk
Metacello new
  baseline: 'Metacello';
  repository: 'github://dalehenrich/metacello-work:master/repository';
  get.
Metacello new
  baseline: 'Metacello';
  repository: 'github://dalehenrich/metacello-work:master/repository';
  onConflict: [:ex | ex allow];
  load
```

**Comment by dalehenrich** [comment]
I can't find a reference to `Metacello-TestsCommonMC.pharo20-dkh.5` in either the builderCI source or the current Metacello configurations/source ... there is a reference to `Metacello-TestsCommonMC.pharo20-dkh.3`???

**Comment by dalehenrich** [comment]
`Metacello-TestsCommonMC.pharo20-dkh.5` is the current version of the Metacello-TestsCommonMC.pharo20 package in the repo itself ... and in the baseline the package is associated with pharo2.0, pharo3.0 and pharo4.0 ...  

What does `BaselineOfMetacello project attributes` produce in Pharo5.0? 

The result of `MetacelloPlatform current defaultPlatformAttributes` would be useful if you don't have the BaselineOfMetacello available...

**Comment by demarey** [comment]
Le 29 mai 2015 à 20:02, Dale Henrichs a écrit :

> Metacello-TestsCommonMC.pharo20-dkh.5 is the current version of the Metacello-TestsCommonMC.pharo20 package in the repo itself ... and in the baseline the package is associated with pharo2.0, pharo3.0 and pharo4.0 ...
> 
> What does BaselineOfMetacello project attributes produce in Pharo5.0?
> 
BaselineOfMetacello is not loaded in Pharo

> The result of MetacelloPlatform current defaultPlatformAttributes would be useful if you don't have the BaselineOfMetacello available...
> 
#(#squeakCommon #pharo #'pharo4.x' #'pharo4.0.x' #'pharo5.x' #'pharo5.0.x')

Note that #pharo4.* will be removed in some time.

**Comment by demarey** [comment]
Le 29 mai 2015 à 19:39, Dale Henrichs a écrit :

> This error Working copy for Metacello-TestsCommonMC.pharo20-dkh.5 not found is possibly due to the fact that the BaselineOfMetacello does not have a spec for #'pharo5.x' (should be added here) ... OTOH (it is very hard for me to read the stack report from the pharo debug log in travis), there might be some confusion in the bootstrapping code ... in which case Metacello must think that it isn't installed yet ...
> 
> Have you been able to manually install Metacello in Pharo5.0 using the following:
> 
> Metacello new
>   baseline: 'Metacello';
>   repository: 'github://dalehenrich/metacello-work:master/repository';
>   get.
> Metacello new
>   baseline: 'Metacello';
>   repository: 'github://dalehenrich/metacello-work:master/repository';
>   onConflict: [:ex | ex allow];
>   load
yes, it works fine.

**Comment by dalehenrich** [comment]
This is beginning to smell like a problem in Metacello for extracting 
the working copy from the package registry ...

Have you tried manually loading Metacello into Pharo50? You should see 
the same problem as we're getting in travis-ci ... If the monticello api 
hasn't significantly changed, this might point to a pharo50 regression...

Dale

**Comment by dalehenrich** [comment]
Do the tests pass?

**Comment by dalehenrich** [comment]
Here's the stack frame where the error is generated:

```
[ self error: 'Working copy for ' , self name , ' not found' ] in MetacelloCachingGoferResolvedReference>>workingCopy
  	Receiver: a MetacelloCachingGoferResolvedReference name: 'Metacello-TestsCommonMC.pharo20-dkh.5'
  	Arguments and temporary variables: 
  		pName: 	'Metacello-TestsCommonMC'
  	Receiver's instance variables: 
  		name: 	'Metacello-TestsCommonMC.pharo20-dkh.5'
  		package: 	'Metacello-TestsCommonMC'
  		author: 	'dkh'
  		branch: 	'pharo20'
  		versionNumber: 	5
  		repository: 	a MCDictionaryRepository(cache)
  		cachedVersion: 	a MCVersion(Metacello-TestsCommonMC.pharo20-dkh.5)
```

Here's code of the method that's signaling the error:

```Smalltalk 
workingCopy
  "Answer a working copy or throw an error if not present."

  | pName |
  cachedVersion == nil
    ifTrue: [ ^ super workingCopy ].
  pName := cachedVersion package name.
  ^ MCWorkingCopy allManagers
    detect: [ :each | pName = each packageName ]
    ifNone: [ self error: 'Working copy for ' , self name , ' not found' ]
```

The error is being generated because there are no working copies whose `packageName` is `Metacello-TestsCommonMC` ... the odd bit is that for some reason, the cachedVersion (present in image, I think) has been set, but presumably it wasn't necessarily cached in `allManagers` ... What package version of  `Metacello-TestsCommonMC` is actually loaded in Pharo5.0?

**Comment by demarey** [comment]
Le 30 mai 2015 � 01:44, Dale Henrichs a �crit :

> Do the tests pass?

Yes, all of them :)

**Comment by demarey** [comment]
Le 30 mai 2015 à 05:58, Dale Henrichs a écrit :

>  What package version of Metacello-TestsCommonMC is actually loaded in Pharo5.0?
> 

Metacello-TestsCommonMC.pharo20-dkh.5

**Comment by demarey** [comment]
Le 1 juin 2015 à 13:49, Christophe Demarey a écrit :

> 
> Le 30 mai 2015 à 05:58, Dale Henrichs a écrit :
> 
>>  What package version of Metacello-TestsCommonMC is actually loaded in Pharo5.0?
>> 
> 
> Metacello-TestsCommonMC.pharo20-dkh.5

Sorry, it is Metacello-TestsCommonMC.pharo20-EstebanLorenzano.4
and its ancestor is Metacello-TestsCommonMC.pharo20-dkh.3 (no change between these 2 versions)

**Comment by demarey** [comment]
In Pharo 50, I tried:
```smalltalk
MCWorkingCopy allManagers
    detect: [ :each | 'Metacello-TestsCommonMC' = each packageName ]
    ifNone: [ self error: 'Working copy not found' ]```
It throws the error because the package is not found

```smalltalk
MCWorkingCopy allManagers
    detect: [ :each | 'Metacello-TestsPharo20MC' = each packageName ]
    ifNone: [ self error: 'Working copy not found' ]```
It gives `a MCWorkingCopy(Metacello-TestsPharo20MC)`

It looks like there is a problem with the package name. The behavior is exactly the same in Pharo 4.0. Do the tests pass for Pharo 4.0 for you (with travis)?

**Comment by dalehenrich** [comment]
On 06/01/2015 05:26 AM, demarey wrote:
>
> In Pharo 50, I tried:
>
> MCWorkingCopy  allManagers
>      detect:  [:each |  'Metacello-TestsCommonMC'  =  each packageName ]
>      ifNone:  [self  error:  'Working copy not found'  ]```
> It  throws the error because the package isnot  found
>
> ```smalltalk
> MCWorkingCopy  allManagers
>      detect:  [:each |  'Metacello-TestsPharo20MC'  =  each packageName ]
>      ifNone:  [self  error:  'Working copy not found'  ]```
> It  gives `aMCWorkingCopy(Metacello-TestsPharo20MC)`
>
> It  looks like there is a problem with the package name.The  behavior is exactly the same inPharo  4.0.Do  the tests pass forPharo  4.0  for you (with travis)?

Only Pharo5.0 is failing ... I can't guess why Pharo4.0 might be loading 
correctly, but the baseline is asking for Metacello-TestsCommonMC to be 
loaded when it looks like Metacello-TestsPharo20MC should be the one 
that is loaded ... And I don't think I have a TestsPharo20MC package on 
git, so that's probably needed before we can get pharo5.0 loaded 
correctly and if Pharo4.0 needs the same package, then the baseline 
should be changed for Pharp4.0 as well (both pharo4.0 and phar5.0 are 
sharing the same packages at this moment) ...

Dale

**Comment by dalehenrich** [comment]
@demarey while working with tODE and STON in pharo3.0 I found that Pharo was getting itself confused by the fact that a class had been moved from one package to another ... it had to do with the fact that the category of the class no longer matched the package that it was member of but PHaro was stubborn about thinking that the class belonged to a different package ... this had to do with the scan of an image that was trying to determine which package a class was in ... it had the same signature where Monticell/Metacello was told by the system that a class was in a package that was no longer valid .... very nasty corner case ...

**Comment by dalehenrich** [comment]
@demarey 

Looks like latest build failed with a [MessageNotUnderstood: FileReference>>closed](https://travis-ci.org/dalehenrich/metacello-work/jobs/70409806#L425):

```
RUNNING TESTS...
==== Startup Error: MessageNotUnderstood: FileReference>>closed
FileReference(Object)>>doesNotUnderstand: #closed
MCMczReader>>zip
MCMczReader>>parseMember:
MCMczReader>>loadPackage
MCMczReader(MCVersionReader)>>package
MCMczReader(MCVersionReader)>>basicVersion
MCMczReader(MCVersionReader)>>version
```

That's an odd place for an error so I'm curious if there's something deeper wrong with FileTree or something?

**Comment by peteruhnak** [comment]
Is there anything I can do to speedup the resolution of this issue?

I unsuccessfully tried to setup a test env locally... but I found that @demarey 's version now doesn't even load in Pharo 50165 (and later) because of this change https://pharo.fogbugz.com/f/cases/15933/Wrong-metacelloPlatformAttributes-for-pharo-5

**Comment by demarey** [comment]
@dalehenrich 
There are currently 2 issues:
- we updated metacelloPlatformAttributes in Pharo 5 from ```#(#squeakCommon #pharo #'pharo4.x' #'pharo4.0.x' #'pharo5.x' #'pharo5.0.x')``` to ```#(#squeakCommon #pharo #'pharo5.x' #'pharo5.0.x')```. It means that metecello may now fallback to load an inappropriate version if no instruction is given for Pharo 5.
- I updated the pharo5.0 branch of filetree to reflect changes in Pharo. If these changes are not present in the pharo image, you may end with MessageNotUnderstood: FileReference>>closed

@peteruhnak 
Metacello works on Pharo 5.0. Just update SmalltalkImage>>#metacelloPlatformAttributes by adding ```#'pharo4.x' #'pharo4.0.x'``` and run ```Metacello new
  baseline: 'Metacello';
  repository: 'github://demarey/metacello-work:master/repository';
  onConflict: [:ex | ex allow];
  load: 'Tests'```
or pick an image [here](https://ci.inria.fr/rmod/job/Metacello-CDrepo/)

I found a missing metacello directive and just did an update on my pull request.

**Comment by dalehenrich** [comment]
I will start looking into this today ...

**Pull request merged**
