### PR TITLE
-  Pick up current WebClient for Squeak

### PR DESCRIPTION
**Pull request by krono**
to actually be able to use Metacello on Mac with SqueakSSL

### CODE REVIEW

**Comment by dalehenrich** [comment]
Restarted https://travis-ci.org/dalehenrich/metacello-work/jobs/46372319, Squeak Trunk is stubbornly refising to be green:)

**Comment by krono** [comment]
yet, I don't know why.
I should look into that

**Comment by dalehenrich** [comment]
I'm rerunning the [build on the configuration branch](https://travis-ci.org/dalehenrich/metacello-work/builds/40801305) just to see since it originally errored out ... the [run before the merge was green](https://travis-ci.org/dalehenrich/metacello-work/builds/40739932) and today I've just run two tests ([1](https://travis-ci.org/dalehenrich/metacello-work/jobs/46640836) and [2](https://travis-ci.org/dalehenrich/metacello-work/jobs/46640837) on a branch from the most recent master and they are both green ... so if the rerun is clean, there might be something in your checkin that is causing the hang ...  the thing with the trunk is that it is a moving target:)

**Comment by dalehenrich** [comment]
The pre-merge build is running clean for squeak-trunk ... looks like the other failing Squeak job will turn green if I retry enough...

**Comment by dalehenrich** [comment]
The [pre-merge build is green](https://travis-ci.org/dalehenrich/metacello-work/builds/40801305) including the trunk build, so it presumably is a problem with the new code

**Comment by krono** [comment]
I just ran all stuff in a current Trunk image and get no problems.
Can you please re-run with `SCREENSHOT=30` so we see where it stalls?
(I can provide an image that processed fine, too)

**Comment by dalehenrich** [comment]
@krono if you add the `SCREENSHOT=30` to your checkout for this pull request the proper travis job will be run and you'll be able to see the results yourself ... If I were to do it I would have to change the master branch which I don't want to necessarily do ...

**Comment by krono** [comment]
silly me. right

**Comment by krono** [comment]
Well this time it went through flawlessly :( https://travis-ci.org/dalehenrich/metacello-work/jobs/47279090

**Comment by krono** [comment]
\o/

**Comment by dalehenrich** [comment]
quick merge before something else changes in the trunk:)

**Comment by krono** [comment]
:D 
I still think this is not _really_ trunk related…
The trunk updates in the last few days are few and surely not related.

But, what do I know, software is hard, ironically

**Comment by dalehenrich** [comment]
Yeah and it was able to pass the pre-web client builds as well ... I'm pretty sure that it is some kind of warning that pops up since Squeak still hangs when that happens and without the proper feedback it is impossible to know...

**Pull request merged**
