### PR TITLE
some cleaning

### PR DESCRIPTION
**Pull request by demarey**

### CODE REVIEW

**Comment by dalehenrich** [comment]
@demarey, it looks like some of your edits are causing test failures on non-Pharo5.0 versions of Pharo(Pharo1.4 through Pharo2.0) ... I'm guessing that sending #asClass to a Symbol is the culprit ... looks like you'll need to change your plan a bit ... I've nothing against having you push methods in **MetacelloPlatform** if you #asClass is preferred in Pharo5.0, but I still expect Metacello to work on the older versions of Pharo, even if you guys don't care.

The other failures appear to be network related ...

**Comment by demarey** [comment]
I though #asClass was present in older versions of Pharo. I will do an update to keep this code working on older versions of Pharo.

**Comment by dalehenrich** [comment]
@demarey the tests are passing now ... are you done with the work you had planned for this PR, or do you have more work planned? 

Could you update Issue #362 with a fresh code critic result? I would really like to get as many of those items cleaned up as possible ...

**Comment by demarey** [comment]
yes, I'm done with this PR.
For Issue #362, I need to add a feature to the critics tool to run the same set of rules as the monkey. I will update the issue when I'm done with that

**Comment by demarey** [comment]
Hi Dale,
In the latest pharo version, I added a way to easily get code critics checked during a Pharo integration.
You need to open the critic browser (world menu/tools), then select metacello packages, click next and then select "Pharo integration rules" and click add, then next.
Let me know if everything is fine.

**Comment by dalehenrich** [comment]
@demarey it would really help me (I am time challenged) if you would update the list of issues for me ... I do not have a pharo5.0 at my fingertips, and I will not likely actually do the work in pharo5.0 itself, for fear of tripping over the bugs ... my plan would be to make the changes using either vi or gemstone ... so I just need to see the code critic output to be able to understand what needs to be changed ...

**Pull request merged**
