### PR TITLE
add Squeak 4.6 & 5.0 platform attributes and update Travis

### PR DESCRIPTION
**Pull request by pdebruic**
This is a copy of Tobias's fix to the defaulPlatformAttributes update for Squeak 4.6 & 5.0

I also added Pharo 4, Squeak 4.6 & 5.0 to the .travis.yml file

### CODE REVIEW

**Comment by dalehenrich** [comment]
@pdebruic looks like we're down to a  [builderCI issue](https://travis-ci.org/dalehenrich/metacello-work/jobs/76679961#L361):

```
+case "$ST" in
+IMAGE_BASE_NAME=Squeak-5.0
+IMAGE_TARGET_NAME=Squeak-5.0
+case "$ST" in
+case "$ST" in
+mv Squeak-5.0.changes ../Squeak-5.0.changes
mv: cannot stat `Squeak-5.0.changes': No such file or directory
The command "./build_image.sh" failed and exited with 1 during .
```

**Comment by pdebruic** [comment]
@dalehenrich  

Yeah I was looking at that and confusing myself.   Then I realized you haven't merged the pull request in Builder CI which fixes Squeak 5.0.   So do that and these two PRs of mine should fix themselves once you re-trigger them on Travis..  

I think.

**Comment by dalehenrich** [comment]
... and I've just merged the Squeak5.0 addition to builderCI, so I will restart the two Squeak5.0 builds ...

**Comment by pdebruic** [comment]
@dalehenrich OK but I think we will need to fix #369 for these to fully pass.

also - Can you restart the build for pr #366 ?

**Comment by dalehenrich** [comment]
#366 is restarted ...

**Comment by dalehenrich** [comment]
@pdebruic, yes we are down to #369 for Squeak 5.0, so if you fix that bug as part of this PR, the master branch will be ready for prime time ... #366 still seems to be having massive failures and I will need to look at things a bit closer

**Comment by krono** [comment]
nice!

**Pull request merged**
